### ISSUE TITLE
exception:character mapping must return integer, None or unicode

### ISSUE THREAD

**Issue by iewgnaw** [qiniu/python-sdk#154]
access_key 和security key 为unicode时， bucket.fetch会出错，必须将unicode转码为ascii
Python 2.7.6 , qiniu==7.0.2

例如：
q = Auth(u'ak', u'sk')
bucket = BucketManager(q)
ret, info = bucket.fetch(url, u'xxx', '1.jpg')

>>> info
exception:character mapping must return integer, None or unicode, status_code:-1, _ResponseInfo__response:None, text_body:None, req_id:None, error:character mapping must return integer, None or unicode, x_log:None

**Comment by longbai** [comment]
@iewgnaw 收到了，多谢，我这边评估下 改进 方案

**Comment by longbai** [comment]
ak, sk 这边只是ascii码，不需要用u，多谢了。
