### ISSUE TITLE
fetch 不能抓取外站图片么

### ISSUE THREAD

**Issue by zongxiao** [qiniu/python-sdk#156]
url = '外站图片地址'
ret, info = bucket.fetch(url, 'name', filename)

返回数据

exception:None, status_code:200, _ResponseInfo__response:<Response [200]>, text_body:{}, req_id:hSAAAGLRA_feHcIT, x_log:QINIUPROXY:33;gS.h:33;uS.cpy:4;s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr;s.ph;s.put.tw;s.put.tr;s.ph;PFDS:1;PFDS:2;PFDS:3;rdb.g/no such key;DBD/404;DBG/404;v4.exist:1/Document not found;rs11_4.ins:1;qtbl.ins:2;mc.s;RS:3;uS.hdo:8;IO:47

**Comment by longbai** [comment]
http://developer.qiniu.com/docs/v6/api/reference/rs/fetch.html 可以，你这个本来 就没有
