### ISSUE TITLE
公开现有 qiniu.utils._etag 函数

### ISSUE THREAD

**Issue by mckelvin** [qiniu/python-sdk#170]
`qiniu.utils.etag` 支持输入文件路径计算hash，`qiniu.utils._etag` 支持输入字节流计算hash。实际使用过程中遇到输入 `StringIO.StringIO` 计算hash的需求，希望能公开这个函数并改个名字，比如叫 `qiniu.utils.etag_stream`。

感谢。

**Comment by longbai** [comment]
收到, 我们来改下

**Comment by longbai** [comment]
closed by #175

**Comment by mckelvin** [comment]
:clap:
