### ISSUE TITLE
put_data函数里的progress_handler其实是没用的？

### ISSUE THREAD

**Issue by bluedazzle** [qiniu/python-sdk#177]
源码里这个函数好像不能分片上传？那要progress_handler这个参数做什么呢？

**Comment by longbai** [comment]
这个后面会实现，不好意思。

**Comment by bluedazzle** [comment]
可以直接按put_file里写分片的写法写吗？我现在需要实现分片二进制流。还有progress_handler的进度数据怎么引用呢？文档里的demo比较简洁，没太明白。

**Comment by ErwinCao** [comment]
https://github.com/qiniu/python-sdk/commit/637704a671b5067243fc96ebd363b48917b7f403
progress进度的返回是可以完成，但是我方考虑python sdk一般是运行在服务端，可能很少有客户需要单独查看文件的上传进度（程序放在后台一直运行上传即可）。
当前可以直接通过 upload_progress_recorder.py中的UploadProgressRecorder对象将4M一块的断点 进行记录，所以上传进度（4M一块是否上传完成）完全可以被断点记录取代，所以也就没有直接提pr，这个需求我们内部需要再协商一下。

**Comment by bluedazzle** [comment]
好的，我们现在就是挂在后台上传。但因为我们的数据是直接从用户本地传到七牛，如果没有进度显示用户体验就比较差。我试下UploadProgressRecorder，谢谢！
