### ISSUE TITLE
上传大文件的时候出现exception:HTTPConnectionPool(host='upload.qiniu.com', port=80): Read timed out.

### ISSUE THREAD

**Issue by rchlin** [qiniu/python-sdk#181]
难道是客户端内存太小吗？

**Comment by longbai** [comment]
请问多大的文件，这个文件最后麻烦看下是否已经传上去了？

**Comment by rchlin** [comment]
345MB以上的都不行，(read timeout=30)。上传的主机内存是768MB。在该主机上传548KB的小文件没有问题，用其他客户端上传也没有问题

**Comment by longbai** [comment]
我们在查了。

**Comment by rchlin** [comment]
经过我检查，应该是vps的python版本问题。装了很多模块以后，现在传送大型文件可以正常使用了，打扰了！

**Comment by longbai** [comment]
好的，多谢支持。
