### ISSUE TITLE
download_private_link无法返回可用链接

### ISSUE THREAD

**Issue by hellflame** [qiniu/python-sdk#184]
按照文档里面的[方法](http://developer.qiniu.com/docs/v6/api/reference/security/download-token.html#download-token-algorithm)

```python
from hashlib import sha1
url = 'http://developer.qiniu.com/resource/flower.jpg?e=1451491200'
secret = 'MY_SECRET_KEY'
print urlsafe_b64encode(hmac.new(url,secret , sha1).digest())
```
```bash
   _wtPUG_vrv3OO3LRNj7W7lju2kM=
```
并不能得到文档所示的url诶 
或者说我的加密方式有错么

**Comment by hellflame** [comment]
已经
```python
from base64 import urlsafe_b64encode
import hmac
```
忘了写

**Comment by longbai** [comment]
汗，你这个是算hmac的 base64 编码，直接用auth里的函数就好

**Comment by hellflame** [comment]
然而在官方文档里面不就是`hmac的base64`么2333333，真的是我理解错误么............=.=
然而对于`pythonsdk`里面给的auth里的函数.....`私有空间`貌似只能用默认域名......并不能用自己设置的域名(自定义域名返回的链接表示`404`).....这是因为只为默认域名解析的缘故么.......

**Comment by forrest-mao** [comment]
@hellflame 可以用自定义域名的私有链接，使用 auth的 private_download_url，第二个参数的url中的path部分要保证是空间中已经存在的key

**Comment by hellflame** [comment]
@forrest-mao 我已经这么做了......之前只是觉得还要用那么长的默认域名比较麻烦........
