### ISSUE TITLE
urlsafe_base64_encode 在 Python2 和 Python 3 下的返回类型不同

### ISSUE THREAD

**Issue by glasslion** [qiniu/python-sdk#190]
在 Python2 下返回值是 str, 在 Python3 下 返回值是 unicode.

这样的话， 那些同时兼容 Python 2/3 的代码，在给会调用到  `urlsafe_base64_encode` 的函数 传递参数时， 必须显式地判断 python 版本 来决定 所传的字符串是否需要encode。会造成很多冗余和代码的丑陋。

例如：
https://github.com/glasslion/django-qiniu-storage/commit/d6984d1764dab746b4c133563494db1dbf51e4eb

**Comment by longbai** [comment]
这个做到完美兼容是有点头疼，您的建议是什么？都用str?

**Comment by glasslion** [comment]
重新读了一边代码，发现我之前的理解有点错误：
```
def urlsafe_base64_encode(data):
    ret = urlsafe_b64encode(b(data))
    return s(ret)
```
`urlsafe_base64_encode` 会先把  data 转换成 `bytes`

**Comment by glasslion** [comment]
再借这个issuse问个问题， 我有个开源项目 [django-qiniu-storage](https://github.com/glasslion/django-qiniu-storage)，让Django框架集成 七牛云存储 , 通过 TravisCI 跑测试时，经常遇到 connect reset, timeout 等问题。 怀疑是中美网络的问题， 已经用了up.qiniug.com， 但效果不明显。 本项目也是 TravisCI, 这方面有什么经验吗？

**Comment by longbai** [comment]
@glasslion 中美网络和 travis 网络都不太好
