### ISSUE TITLE
[bug?]when download .tmp suffix file from qiniu, the filesize is not correctly

### ISSUE THREAD

**Issue by smileboywtu** [qiniu/python-sdk#195]
let's say i have a file 100K, the mime type is application/tar and the filename is qiniu.tmp. after i download the file the content length is actually 101888 less than 102400.

**Comment by longbai** [comment]
麻烦发工单 发下详情，谢谢。

**Comment by smileboywtu** [comment]
(2.7) ➜  Downloads http get http://7xscok.com1.z0.glb.clouddn.com/qiniu_test.png\?attname\=
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Log, X-Reqid
Access-Control-Max-Age: 2592000
Cache-Control: public, max-age=31536000
Connection: keep-alive
Content-Disposition: attachment; filename="qiniu_test.png"
Content-Length: 102400
Content-Transfer-Encoding: binary
Content-Type: application/x-tar
Date: Wed, 13 Apr 2016 06:47:26 GMT
ETag: "FjeLA8SmEnIFXED5Q2jwfVSLv23Z"
Last-Modified: Wed, 13 Apr 2016 06:28:39 GMT
Server: nginx/1.8.0
X-Log: mc.g;IO:1
X-Qiniu-Zone: 0
X-Reqid: 3mkAAELNWd1a10QU
X-Via: 1.1 fuzhou52:80 (Cdn Cache Server V2.0), 1.1 zhoudxin64:8 (Cdn Cache Server V2.0)



+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+

(2.7) ➜  Downloads http get http://7xscok.com1.z0.glb.clouddn.com/qiniu_test.tmp\?attname\=
HTTP/1.1 200 OK
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Log, X-Reqid
Access-Control-Max-Age: 2592000
Age: 1
Cache-Control: public, max-age=31536000
Connection: keep-alive
Content-Disposition: attachment; filename="qiniu_test.tmp"
Content-Length: 101888
Content-Transfer-Encoding: binary
Content-Type: application/x-tar
Date: Wed, 13 Apr 2016 06:21:51 GMT
ETag: "FjMODLP-NH25rz9TVF2UgWHfivDO"
Last-Modified: Tue, 12 Apr 2016 10:42:04 GMT
Server: nginx/1.4.4
X-Log: mc.g/404;mc.g/404;rs19_9.sel;qtbl.get;RS.dbs;mc.s;RS:1;mc.s;IO:4
X-Qiniu-Zone: 0
X-Reqid: yT8AANHR0NCSlkQU
X-Via: 1.1 fzh56:8080 (Cdn Cache Server V2.0), 1.1 hzhdx192:0 (Cdn Cache Server V2.0)

**Comment by smileboywtu** [comment]
工单是什么 ？

**Comment by smileboywtu** [comment]
just rename the file, it works well

**Comment by longbai** [comment]
这本来就是两个文件啊

**Comment by smileboywtu** [comment]
一个文件我改了后缀 就出现了这个问题， 你可以自己试一试

**Comment by lilanjun2016** [comment]
这两个文件的ETAG值不相同的，所以应不是一个文件，您那边也看下
