### ISSUE TITLE
上传大文件的时候自动输出时间戳等

### ISSUE THREAD

**Issue by hellflame** [qiniu/python-sdk#196]
[这里](https://github.com/qiniu/python-sdk/blob/master/qiniu/services/storage/uploader.py)的`_Resume`类在初始化的时候自动print 了两个时间戳，能不能隐藏一下。。。。首先这两个print应该没有什么作用的吧，然后，，，我在终端调用这样自动print东西出来我会比较难处理

```
print(self.modify_time)
print(modify_time)
```

然后还有另一个地方

```
def record_upload_progress(self, offset):

print(record_data)
```

能不能把这些输出都去掉讷。

好吧，我的终端处理上传的时候暂时没有处理进度条，难道这是会产生输出的原因么。。。。

**Comment by hellflame** [comment]
好吧，，，其实还有另一个严重的问题就是，无人值守的自动上传已经连续好几个月失败了，虽然不知道是不是因为这些多余的输出的问题，，，我之后再测试好了。。。。

**Comment by longbai** [comment]
OK, Thanks

**Comment by hellflame** [comment]
自己已经实现了更基础的处理响应的方法，没有依赖SDK的requests

https://github.com/hellflame/qiniu_manager
