### ISSUE TITLE
https支持吗？

### ISSUE THREAD

**Issue by gaocaifang** [qiniu/python-sdk#201]
python SDK是否支持https上传文件？若支持https，需要修改那里啊？官方的文档里一直没找到Python SDK是怎么支持https的。能否简单给个示例或者讲解一下需要哪里修改一些配置？

**Comment by longbai** [comment]
没有做限制，可以的

**Comment by gaocaifang** [comment]
您好，若支持https，需要修改那里啊？官方的文档里一直没找到Python SDK是怎么支持https的。能否简单给个示例或者讲解一下需要哪里修改一些配置？

**Comment by longbai** [comment]
上传域名改一下就可以, 使用https://up.qbox.me
