### ISSUE TITLE
list操作的实现是否有问题？

### ISSUE THREAD

**Issue by EnixCoda** [qiniu/python-sdk#203]
刚刚尝试了Python SDK，list同样的内容，CPU一个核心会满载半分钟，绝大部分时间都在执行http.py中的__return_wrapper函数

相比之下，在PHP SDK中，进行一次bucket内1000个文件的list请求，可以瞬间完成。
是不是Python SDK有些缺陷？

```
# -*- coding: utf-8 -*-

from qiniu import Auth
from qiniu import BucketManager

AK = ""
SK = ""
BUCKET_NAME = ""

auth = Auth(AK, SK)
bucket = BucketManager(auth)
response, eof, info = bucket.list(BUCKET_NAME, None, None, 1000, None)
```

**Comment by longbai** [comment]
收到，有些奇怪，这里并没有做什么神奇的操作，我们看下

**Comment by ExinCoda** [comment]
过了这么久，刚刚重新试了试，这个问题还是没有解决……

改天我还是自己看看代码找找问题吧orz

**Comment by ExinCoda** [comment]
找到问题所在了

http.py的`__return_wrapper`函数中使用了requests的`json()`函数，[这个链接](http://stackoverflow.com/questions/32016218/performance-issues-formatting-using-json)中提到requests的charset检测耗费了大量时间。

进行如下修改可以让本来消耗1分钟的json()加快到“瞬间”完成（内容为list的1000个文件）。
````
def __return_wrapper(resp):
    if resp.status_code != 200 or resp.headers.get('X-Reqid') is None:
        return None, ResponseInfo(resp)
    resp.encoding = 'UTF-8' # 增加这一行
    ret = resp.json() if resp.text != '' else {}
    return ret, ResponseInfo(resp)
````

**Comment by longbai** [comment]
👍👍👍 👍  十分感谢

**Comment by jemygraw** [comment]
fixed in https://github.com/qiniu/python-sdk/pull/261
