### ISSUE TITLE
[bug] put_data 上传图片成功但全部损坏

### ISSUE THREAD

**Issue by zoucaitou** [qiniu/python-sdk#214]
环境

1.  python 2.7
2. pip install qiniu 7.0.8
3. mac osx 10.11.6
4 .测试代码如下

# -*- coding: utf-8 -*-

from qiniu import Auth, put_data, etag, urlsafe_base64_encode
import qiniu.config

access_key = 'xxxxx'
secret_key = 'xxxxx'

q = Auth(access_key, secret_key)

bucket_name = 'image'

key = 'my-python-logo.jpg';

token = q.upload_token(bucket_name, key, 3600)

localfile = 'http://img.cnsofas.com/im/201605/2016591634827001.jpg'
ret, info = put_data(token, key, localfile)
print ret
print info

5. 输出结果如下<br/>
{u'hash': u'Fl4us-uivWV9JwN0tNRSJX2bBeR0', u'key': u'my-python-logo.jpg'}
exception:None, status_code:200, _ResponseInfo__response:<Response [200]>, text_body:{"hash":"Fl4us-uivWV9JwN0tNRSJX2bBeR0","key":"my-python-logo.jpg"}, req_id:llQAABOh7t7FJWgU, x_log:s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr;s.ph;s.put.tw;s.put.tr;s.ph;PFDS;PFDS:1;PFDS:2;rs22_6.sel/not found;rs21_6.sel/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs22_6.ups;qtbl.ups:1;mc.s;RS:2;rs.put:3;rs-upload.putFile:8;UP:9

图片成功上传到七牛，但是全部损坏

**Comment by zoucaitou** [comment]
@longbai  求帮忙

**Comment by longbai** [comment]
收到，我们看下

**Comment by forrest-mao** [comment]
hi，@zoucaitou 如果要上传具体 URL 中的数据的话，可以使用 
py2: data = urllib.urlopen("http://img.cnsofas.com/im/201605/2016591634827001.jpg")
py3: data = urllib.request.urlopen("http://img.cnsofas.com/im/201605/2016591634827001.jpg")

然后使用 ret, info = put_data(token, key, data) 就行

**Comment by zoucaitou** [comment]
@forrest-mao 上传成功，没有损坏。但是预览不了，是跟临时域名有关系吗？

**Comment by zoucaitou** [comment]
谢谢两位，问题解决了
