### ISSUE TITLE
list函数同时使用limit和delimiter的逻辑有问题

### ISSUE THREAD

**Issue by xiazhujie** [qiniu/python-sdk#215]
我要模拟目录的实现,期望的是能够返回指定前缀作为父目录的直属子目录和文件.
前缀为GYyMYR/images/,分隔符为"/"的应该是GYyMYR/images/20160407/的形式,也就是按日期归类的.
因此下面的 list 操作不会有实际文件的key,应该都是类似目录的.

bucket.list(bucket_name, prefix="GYyMYR/images/", marker=marker, limit=100, delimiter="/")
可以列出我的四个目录(这是正常的):
GYyMYR/images/20160407/
GYyMYR/images/20160411/
GYyMYR/images/20160807/
GYyMYR/images/20160812/

bucket.list(bucket_name, prefix="GYyMYR/images/", marker=marker, limit=1, delimiter="/")
可以列出我的1个目录(这是正常的):
GYyMYR/images/20160407/

bucket.list(bucket_name, prefix="GYyMYR/images/", marker=marker, limit=2, delimiter="/")
只列出我的1个目录(**出问题的**):
GYyMYR/images/20160407/
想要显示两个的话,limit是25才行
显示3个,limit需要是43

分析结果是,七牛的逻辑处理有问题,limit之所以不好用是因为在查询的时候把过滤掉的文件数量也计算在内了,比如说,limit为1的时候正常是因为第一个文件的前缀就符合,而limit为25的时候才能显示2个目录是因为第一个目录中包含了24个文件,过滤的时候已经计数了,这就是问题的所在.limit应该限制返回的key数量,而不该计算过率掉的文件数量

这应该是服务端的问题

作为变通的方式是获取指定目录的所有子目录和文件,自己过滤出目录,也就是 commonPrefixes ,然后再拼接第一次获取数据的文件数据才能得到指定目录下所有直属的子目录和文件列表,但是无形中增加了API的调用次数和处理复杂度

**Comment by longbai** [comment]
收到，我们看下
