### ISSUE TITLE
没有自己的 Exception 类型

### ISSUE THREAD

**Issue by zxygentoo** [qiniu/python-sdk#217]
一个建议：定义自己的异常类型，在抛异常时抛自己的，并精细错误检查，而不是直接 catch Exception。这样可以把实际出现的异常描述的更清楚，客户端也更容易使用。从库设计的角度看，暴露下层细节（比如 requests），一般也不是太好的做法。

**Comment by longbai** [comment]
谢谢建议，目前是采用返回的错误码。 使用异常 在做内部错误处理比较麻烦，比如catch 异常重试 ，所以采用了返回码的方式。 暴露细节这个确实有欠考虑，后面有机会会调整。

**Comment by zxygentoo** [comment]
嗯，现在的处理方法看得出可能是沿用的主系统的 go 风格，不过既然是 sdk，接近客户端语言的习惯一般都会更顺一点。我现在实际用起来基本都是先判断一下错误码，然后再自己抛一个合适的 HTTP 或者 Requests 异常，其实挺别扭的。

不过考虑到兼容性也确实不是很好改，如果以后做大版本升级可以考虑一下。

**Comment by lilanjun2016** [comment]
谢谢你的建议。
