### ISSUE TITLE
验证信息出现问题的情况下依然会报错

### ISSUE THREAD

**Issue by HuangSuoyuan** [qiniu/python-sdk#220]
在生成上传token的时候，使用错误的验证信息时，依然会返回一个token

**Comment by longbai** [comment]
能麻烦给下具体的说明么？是说ak, sk 给错了也能生成token的意思么？

**Comment by HuangSuoyuan** [comment]
嗯嗯，是的，在生成上传token的时候，ak，sk给错了也会生成token
看代码里面，貌似是生成的时候直接本地生成了一个，没有网络请求

**Comment by longbai** [comment]
这个不会进行网络请求的，sdk里只会做些简单的检查，因为这个就是字符串。
