### ISSUE TITLE
本地etag算的值和返回的hash值不一致

### ISSUE THREAD

**Issue by HuangSuoyuan** [qiniu/python-sdk#221]
本地etag值:lto5o-5ea0sNMlW_75VgGJCv2AcJ
返回的hash值:Fto5o-5ea0sNMlW_75VgGJCv2AcJ

返回的信息如下
exception:None, status_code:200, _ResponseInfo__response:<Response [200]>, text_body:{"hash":"Fto5o-5ea0sNMlW_75VgGJCv2AcJ","key":"_tmp_key_for_qiniu_upload_test_no_one_would_use_this_"}, req_id:FUIAAA6gfryo1HMU, FUIAAA6gfryo1HMU, x_log:s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr;s.ph;PFDS;PFDS;rs24_9.sel;qtbl.ins/same entry;rs24_9.sel;qtbl.get;MQ;RS.not:;RS:2;rs.put:8;rs-upload.putFile:9;UP:10;UP:10

**Comment by HuangSuoyuan** [comment]
文件是通过tempfile.mkstemp()生成，里面没有写入内容

**Comment by forrest-mao** [comment]
hi，是否可以帮忙提供下本地 etag 生成的代码， `本地etag值:lto5o-5ea0sNMlW_75VgGJCv2AcJ` 这个计算的 etag 应该是错误的。

**Comment by HuangSuoyuan** [comment]
tempfd, tempfn = tempfile.mkstemp(".tmp")
from qiniu import put_file, etag
local_etag = etag(tempfn)

**Comment by lilanjun2016** [comment]
你好
这个源文件你还在么，能否发下url链接帮看下。

**Comment by HuangSuoyuan** [comment]
现在这个问题貌似修复了，返回的hash值和本地计算的etag一致

**Comment by lilanjun2016** [comment]
好的。
