### ISSUE TITLE
因为没有$HOME导致异常

### ISSUE THREAD

**Issue by hunter007** [qiniu/python-sdk#225]
```
up_hosts = self.get_up_host(ak, bucket)
  File "/home/ubuntu/.pyenv/versions/3.5.2/envs/youlun/lib/python3.5/site-packages/qiniu/zone.py", line 49, in get_up_host
    bucket_hosts = self.get_bucket_hosts(ak, bucket)
  File "/home/ubuntu/.pyenv/versions/3.5.2/envs/youlun/lib/python3.5/site-packages/qiniu/zone.py", line 71, in get_bucket_hosts
    bucket_hosts = self.get_bucket_hosts_to_cache(key)
  File "/home/ubuntu/.pyenv/versions/3.5.2/envs/youlun/lib/python3.5/site-packages/qiniu/zone.py", line 91, in get_bucket_hosts_to_cache
    self.host_cache_from_file()
  File "/home/ubuntu/.pyenv/versions/3.5.2/envs/youlun/lib/python3.5/site-packages/qiniu/zone.py", line 107, in host_cache_from_file
    path = self.host_cache_file_path()
  File "/home/ubuntu/.pyenv/versions/3.5.2/envs/youlun/lib/python3.5/site-packages/qiniu/zone.py", line 124, in host_cache_file_path
    return home + "/.qiniu_pythonsdk_hostscache.json"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by hunter007** [comment]
使用supervisor启动进程，一些变量在python是看不到的，虽然可以通过supervisor配置，但不是最好的解决方案，建议cache文件放到别的目录，比如/tmp或者/var

**Comment by LoveShun** [comment]
有2种办法解决这个问题：
1. 事先使用`os.environ`给设置名为`"HOME"`的环境变量，如`os.environ["HOME"] = "./"`，这样就`os.getenv("HOME")`得到的就是你设置的环境变量了
2. `os.getenv()`可以设置默认值，在没有找到环境变量时就取默认值。
可以把zone.py中的`home = os.getenv("HOME")`改下，如设置默认值为当前路径`home = os.getenv("HOME", "./")`，这样就可以正常运行了
推荐第1种，不要去改别人的代码

**Comment by hunter007** [comment]
不是没有$HOME，而是在有些情况下没有被export到子进程，例如supervisor。
目前看来，只要supervisor和qiniu一起用，肯定会出问题。
为什么supervisor没有export $HOME，我没有详细了解，猜测和deamon进程有关。
我现在的解决办法是在supervisor的配置文件中专门设置一次$HOME。但这明显不是好办法。对于不熟悉supervisor的人，就变成坑了。

**Comment by shidephen** [comment]
这个问题在Windows下必然出现

**Comment by longbai** [comment]
我们在改，不好意思

**Comment by ingping-repos** [comment]
问题解决了吗？ @longbai

**Comment by lxstar** [comment]
这个问题今天又遇到了,  真正部署的时候, 没有几个人会用root启动自己的server.
所以只要部署就会报错的..

> [Errno 13] Permission denied: '/root/.qiniu_pythonsdk_hostscache.json'

**Comment by hellflame** [comment]
```
import os
os.path.expanduser("~")
```
这样获取home目录的话，应该在windows下也会得到正常的结果

**Comment by joway** [comment]
我也遇到了这个问题 , 同 supervisor 启动 , 请问如何解决, 哪怕是暂时性的解决方案也行 ?

**Comment by hunter007** [comment]
@joway ,在supervisor的environ中把HOME传进去，这样可以暂时解决

**Comment by longbai** [comment]
最新版已经改掉了，很抱歉给大家带来麻烦

**Comment by kevin2seedlink** [comment]
@longbai 你好，今天升到最新的SDK，问题就来了，天坑。我们用django+celery，七牛的SDK会在django的view和celery的task里面都使用，django和celery分别使用两个用户启动。所以现在统一放在/tmp下面也会产生权限问题。我们暂时回退至7.0.9。这个缓存文件最好是能够让用户指定：1. 是否使用缓。2. 如果使用，用户自己指定文件地址。

**Comment by lilanjun2016** [comment]
收到您的反馈。
