### ISSUE TITLE
windows下执行报错

### ISSUE THREAD

**Issue by uugign** [qiniu/python-sdk#226]
File "D:\file\Python34\lib\site-packages\qiniu\zone.py", line 124, in host_cache_file_path
    return home + "/.qiniu_pythonsdk_hostscache.json"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
同样的代码在mac上执行是ok的

**Comment by 837278709** [comment]
https://github.com/837278709/python-sdk
it is fixed under this fork.
