### ISSUE TITLE
put_data 超过 10M 就报 message too large

### ISSUE THREAD

**Issue by Knight-ZXW** [qiniu/python-sdk#227]
why?

code like
text = b'a'_1024_1024*10
ret, info = put_data(token, key, text)

**Comment by nimdanoob** [comment]
exception:None, req_id:WQcAAMlddxMPu3wU, WQcAAMlddxMPu3wU, status_code:400, error:invalid multipart format: multipart: message too large, _ResponseInfo__response:<Response [400]>, x_log:UP:115/400;UP:142/400, text_body:{"error":"invalid multipart format: multipart: message too large"}

**Comment by lilanjun2016** [comment]
400错误可能出现的问题，400 请求报文格式错误（包括上传时，上传表单格式错误；URL 触发图片处理时，处理参数错误；资源管理操作或触发持久化处理（pfop）操作请求格式错误）。

**Comment by jemygraw** [comment]
无法重现该问题。
