### ISSUE TITLE
cannot import name 'Auth'

### ISSUE THREAD

**Issue by xiaoting6** [qiniu/python-sdk#229]
ubuntu 14.04 ，python 3.4.5，import qiniu，没问题，但是 from qiniu import Auth就会报错。

**Comment by lilanjun2016** [comment]
升级下sdk版本，新版sdk如上导入是没有问题的。

**Comment by 64yang** [comment]
macOS Sierra python3.5 from qiniu import Auth就会报错 依旧出错
