### ISSUE TITLE
铁通网络无法访问 https://uc.qbox.me

### ISSUE THREAD

**Issue by eshow101** [qiniu/python-sdk#230]
导致无法上传文件

**Comment by longbai** [comment]
现在还不行么？ 可以用 upload-z0.qbox.me 的https 上传

**Comment by lilanjun2016** [comment]
你指的是https://up.qbox.me吧。
如果铁通网络无法上传，可否直接控制台上传，或是使用http://up.qiniu.com之类的http域名上传试试。
