### ISSUE TITLE
Python3 下上传大文件必定失败

### ISSUE THREAD

**Issue by aisk** [qiniu/python-sdk#236]
上传一个 30M 的文件，必定失败，错误：

```python3
Traceback (most recent call last):
  File "a.py", line 8, in <module>
    ff.save()
  File "/Users/asaka/Codes/lc-python-test/venv/lib/python3.5/site-packages/leancloud/file_.py", line 209, in save
    self._save_to_qiniu(content['token'], content['key'])
  File "/Users/asaka/Codes/lc-python-test/venv/lib/python3.5/site-packages/leancloud/file_.py", line 158, in _save_to_qiniu
    raise LeanCloudError(1, 'the file is not saved, qiniu status code: {0}'.format(info.status_code))
leancloud.errors.LeanCloudError: LeanCloudError: [1] the file is not saved, qiniu status code: -1
```

观察网络请求：

![fj4estmpav8ollsnlvrzplpfdccc](https://cloud.githubusercontent.com/assets/699636/20661101/e426f96c-b587-11e6-86f7-3e399d333942.png)

似乎到 8M 左右就必然会请求失败，然后重试，达到最大重试次数就报错。

**Comment by hellflame** [comment]
等等，，，你真的确定`leancloud/file_.py`这个文件在这个项目中出现了么，，，

最近貌似七牛云的接口有调整的样子(我直接调用了服务器API，貌似一直可以用的样子)，也许是SDK没有更新吧

**Comment by aisk** [comment]
@hellflame 不好意思，贴的错误日志有误导，这里是七牛 SDK 抛出来的异常，被 LeanCloud SDK 捕获之后重新抛出来了。

**Comment by hellflame** [comment]
看到这里每一个请求的返回值长度都是0，觉得这应该就是七牛云的API接口发生变更了的结果

当然我不是指上传接口，而是其他接口。比如获取文件列表，删除资源等一些操作，以前这些操作发生错误的时候会返回一个关于错误信息的json，但是现在直接没有返回内容了，也许报错信息都放到header里面了

最后，觉得这个问题不是应该提前给 这个`LeanCloud SDK`提issue么(好吧，我并不是这个项目的管理员之一，我只是说说而已，单凭上面的报错日志的话，，并不能看出什么的吧，如果我是管理员，我也是不知所措......)

但是，更新qiniu sdk也许有帮助

**Comment by aisk** [comment]
我是 LeanCloud SDK 的开发者，这个 issue 已经定位到了是七牛 SDK 的问题，所以来这里提的 issue。七牛 SDK 已经更新到最新。

**Comment by hellflame** [comment]
![image](https://cloud.githubusercontent.com/assets/7326970/20753538/d36c4454-b741-11e6-94e1-80cc826d1ad8.png)

看了一下，，貌似这个SDK根本就不支持py3的样子，至少在Auth模块里就引用了py3里面没有urllib3的样子，，， @aisk

**Comment by aisk** [comment]
urllib3 是 requests 自己 vender 的: https://github.com/kennethreitz/requests/tree/master/requests/packages

**Comment by hellflame** [comment]
![image](https://cloud.githubusercontent.com/assets/7326970/20754600/ac4387ca-b746-11e6-90a7-791416aa9cde.png)

虽然的确是写着兼容py3，但这应该都没有通过测试的吧

**Comment by aisk** [comment]
https://github.com/qiniu/python-sdk/blob/master/.travis.yml#L6-L7

**Comment by hellflame** [comment]
不看这些写上去的文本信息，实际测试就是不行，这是事实。。。。

**Comment by aisk** [comment]
https://travis-ci.org/qiniu/python-sdk

**Comment by hellflame** [comment]
好吧，无论如何，我应该是不会用这个SDK了(如果个人项目要支持py3的话)

![image](https://cloud.githubusercontent.com/assets/7326970/20757942/2b6d7982-b753-11e6-9f41-a543894f30a3.png)

只要服务器端API不变，我就不会受影响

竟然通过这个issue发现py3的问题也是意外。。。。

**Comment by longbai** [comment]
这个上传有py3的单元测试通过的，我们仔细看下

**Comment by jemygraw** [comment]
我在 Python 3.6.1 下面测试通过了。40MB的文件，如果有问题，欢迎加入343822521 群讨论。

**Comment by jemygraw** [comment]
```
leancloud.errors.LeanCloudError: LeanCloudError: [1] the file is not saved, qiniu status code: -1
```
这个 `-1` 是一个默认的状态码，说明请求没有发出去，需要看看是不是网络问题。
