### ISSUE TITLE
上传png图片时报错

### ISSUE THREAD

**Issue by huanglong123** [qiniu/python-sdk#238]
报错信息：PermissionError: [Errno 13] Permission denied: '/home/xing/.qiniu_pythonsdk_hostscache.json'

很奇怪啊，上传png文件怎么会要写入文件到home目录下的，线下png文件上传没问题，线上的时候报这个错误

**Comment by huanglong123** [comment]
我看了下sdk的源码
    def host_cache_file_path(self):
        home = os.getenv("HOME")
        return home + "/.qiniu_pythonsdk_hostscache.json"

os.getenv("HOME")在我的服务器获取到的是/home/xing, 程序是没权限在这个目录操作的，能否这里不要写死，换成可以配置的啊

**Comment by songfei9315** [comment]
hi 你更新下sdk版本，这个问题已经修复了
