### ISSUE TITLE
批量删除

### ISSUE THREAD

**Issue by liubinbinZpan** [qiniu/python-sdk#243]
可以根据目录批量删除么？
我的单个文件可以删除，提供目录，提示
"no such file or directory"

**Comment by lilanjun2016** [comment]
您使用的这个接口删除的么，
POST /delete/<EncodedEntryURI> HTTP/1.1
Host:           rs.qiniu.com
Content-Type:   application/x-www-form-urlencoded
Authorization:  QBox <AccessToken>
这个只能以单个文件删除。

**Comment by liubinbinZpan** [comment]
嗯  我直接照着python的example写的，
有其他接口可以批量操作么？

**Comment by lilanjun2016** [comment]
您说的以前缀删除这个，需要您自己先把文件列举一下，然后将那个前缀的筛选出来再删除按个删除这个文件。

**Comment by liubinbinZpan** [comment]
嗯  list一下然后在删除 .  谢了

**Comment by lilanjun2016** [comment]
不客气的。
