### ISSUE TITLE
CdnManager的bug

### ISSUE THREAD

**Issue by joneiy** [qiniu/python-sdk#246]
使用CdnManager的get_log_list_data方法，返回如下错误
exception:None, status_code:400, _ResponseInfo__response:<Response [400]>, text_body:{"code":400000,"error":"invalid params: day"}, req_id:ZFIAAMvIHKpYFqMU, ZFIAAMvIHKpYFqMU, error:invalid params: day, x_log:FUSIONLOGMGR/400;APIS:1/400

核对源码发现request的参数与文档上描述不符，req.update({"startDate": log_date})

修改以后可以正常获得数据

**Comment by jemygraw** [comment]
thx, fixed in https://github.com/qiniu/python-sdk/pull/260
