### ISSUE TITLE
KeyError: 'http'

### ISSUE THREAD

**Issue by jachinpy** [qiniu/python-sdk#247]
76         hosts = compat.json.loads(self.bucket_hosts(ak, bucket))
     77 
     78        scheme_hosts = hosts[self.scheme]
     79         bucket_hosts = {
     80             'upHosts': scheme_hosts['up'],

如果生成了用户，AK和SK正确，但是没有创建存储空间，则会报这个错误。

**Comment by jemygraw** [comment]
当然，如果空间不存在，查询上传域名的结果是：
```
{
  "error": "no such bucket"
}
```
无法解析为合法域名，就报错了。
