### ISSUE TITLE
example里的move_to.py 错误

### ISSUE THREAD

**Issue by bernieyangmh** [qiniu/python-sdk#250]
22行

        ret, info = bucket.move(bucket_name, key, bucket, key2)

应该是

        ret, info = bucket.move(bucket_name, key, bucket_name, key2)

**Comment by loyachen** [comment]
多谢指出。我们改下。

**Comment by jemygraw** [comment]
fixed in https://github.com/qiniu/python-sdk/commit/49c05c3972ffe8ea6ab643748532d2f759e5a206
