### ISSUE TITLE
CdnManager 的 get_log_list_data() 报错 invalid params: day

### ISSUE THREAD

**Issue by Esec** [qiniu/python-sdk#255]
不清楚是不是接口改过，现在继续用startDate的时候会报错
`_ResponseInfo__response:<Response [400]>, exception:None, status_code:400, text_
body:{"code":400000,"error":"invalid params: day"}, req_id:_DMAAJmaSxt2h64U, _DM
AAJmaSxt2h64U, x_log:FUSIONLOGMGR/400;APIS:1/400, error:invalid params: day`
<strike>我把C:\Program Files\Python36\Lib\site-packages\qiniu\services\cdn\__pycache__里的.pyc缓存删掉，</strike>qiniu\services\cdn\manager.py第154行的

> req.update({"startDate": log_date})

换成

> req.update({"day": log_date})

然后，问题好像解决了<hr />edit: 我错了_(:зゝ∠)_

**Comment by darrenfantasy** [comment]
exception:None, status_code:400, _ResponseInfo__response:<Response [400]>, text_body:{"code":400000,"error":"invalid params: day"}, req_id:R2YAADou9Oun6sMU, R2YAADou9Oun6sMU, error:invalid params: day, x_log:FUSIONLOGMGR/400;APIS:1/400
遇到了同样的问题

**Comment by Esec** [comment]
Resolved in https://github.com/qiniu/python-sdk/commit/3655d944f5237ce9cc29b7f30ec826a92a374eac

目前master分支的代码已经修复了这个bug，但是v7.1.2的release还没包含这个更新，如果是自己用，可以按照这条issue里面提出的建议直接修改文件，如果是生产服务器，请咨询一下项目管理看该怎么处理这个问题。


________________________________
发件人: yuanda Wang <notifications@github.com>
发送时间: 2017年6月1日 14:14
收件人: qiniu/python-sdk
抄送: Esec; Author
主题: Re: [qiniu/python-sdk] CdnManager 的 get_log_list_data() 报错 invalid params: day (#255)


exception:None, status_code:400, _ResponseInfo__response:<Response [400]>, text_body:{"code":400000,"error":"invalid params: day"}, req_id:R2YAADou9Oun6sMU, R2YAADou9Oun6sMU, error:invalid params: day, x_log:FUSIONLOGMGR/400;APIS:1/400
遇到了同样的问题

―

**Comment by jemygraw** [comment]
@Esec 我们尽快发布。

**Comment by jemygraw** [comment]
已发布，新版本7.1.4  https://pypi.python.org/pypi/qiniu
