### ISSUE TITLE
CdnManager 的 get_log_list_data() 报错 invalid params: day

### ISSUE THREAD

**Issue by darrenfantasy** [qiniu/python-sdk#264]
exception:None, status_code:400, _ResponseInfo__response:<Response [400]>, text_body:{"code":400000,"error":"invalid params: day"}, req_id:uQ8AAFgoa1Or68MU, uQ8AAFgoa1Or68MU, error:invalid params: day, x_log:FUSIONLOGMGR/400;APIS:2/400

**Comment by bernieyangmh** [comment]
麻烦提供一下传入的两个参数的值

**Comment by darrenfantasy** [comment]
domains = 'static.biaoqingmm.com'
log_date = '2017-05-28'

**Comment by darrenfantasy** [comment]
找到原因了 是因为直接用pip install qiniu的库就有问题，应该是你们没有更新！！！

**Comment by tiaobug** [comment]
果然是这个错，pip里没有更新导致了这个错，直接用源码安装就没有问题了。

**Comment by jemygraw** [comment]
this is fixed in 7.1.4
