### ISSUE TITLE
zone.Zone() 指定 up_host 、up_host_backup 等无效

### ISSUE THREAD

**Issue by sxci** [qiniu/python-sdk#271]
zone.Zone() 指定 up_host 、up_host_backup 等无效，全部是通过 uc.qbox.me 查询的结果
![a56ba7d0-194c-4eaf-8b10-ffb087151c80](https://user-images.githubusercontent.com/2267508/27021317-0fafee9a-4f7a-11e7-99ca-73fabd09f4a6.png)

**Comment by jemygraw** [comment]
fixed in https://github.com/qiniu/python-sdk/commit/af8f9ae7bb813e9fe60c416f987099d325e46a2d
