### ISSUE TITLE
put_data 之前是支持上传一个 file like 的 object 的，7.1.5 默认检查 crc 之后就不支持了

### ISSUE THREAD

**Issue by aisk** [qiniu/python-sdk#281]
之前可以上传一个 file like 的 object，比如 `io.BytesIO`，这两天发布的 7.1.5 默认检查上传文件的 crc32，然而这个检查函数只能支持传入 bytes like 的 object，导致所有调用这个方法的代码全都出了问题。

https://github.com/qiniu/python-sdk/blob/d5fa0416128430b990a1b87719277dae6c42c223/qiniu/services/storage/uploader.py#L30

**Comment by jemygraw** [comment]
这个我们跟进看看，主要是为了加上默认的crc32校验。

**Comment by jemygraw** [comment]
你们的代码方便把io.BytesIO转换为byte上传么？

**Comment by aisk** [comment]
是提供给用户的 SDK 用到了这个方法，要保证已经发布的版本的兼容性的。并且转换为 byte，以后也没有办法支持流式上传了。

**Comment by aisk** [comment]
@jemygraw 这个大概多久能解决呢？

**Comment by jemygraw** [comment]
我们尽快看下

**Comment by jemygraw** [comment]
fixed in 7.2.0
