### ISSUE TITLE
对象存储支持流式下载吗？

### ISSUE THREAD

**Issue by Erician** [qiniu/python-sdk#287]
使用r = requests.get(private_url)去下载文件，r.content包含的是文件的内容，r.content是流式的吗？因为我并不想把文件保存到本地，只想按行读取。谢谢

**Comment by bernieyangmh** [comment]
您好，r.content在python3是bytes，可以用下面方式打印
```
import requests
import io


r = requests.get("https://ss0.bdstatic.com/5aV1bjqh_Q23odCf/static/superman/img/logo/bd_logo1_31bdc765.png")

print(r.content)
f = io.BytesIO(r.content)

l = f.readline()
while l:
    print(l)
    l = f.readline()

```

在python2是str，打印出来是乱码.

**Comment by Erician** [comment]
thank you for your reply,it is perfect with your code to read a line.But for a big file,downloading it  would cost a lot of time,and can I use readline without downloading,like streaming?

**Comment by jemygraw** [comment]
用f.read读取一个buffer，然后再读一个buffer
```
read(...)
    read([size]) -> read at most size bytes, returned as a string.

    If the size argument is negative, read until EOF is reached.
    Return an empty string at EOF.
```
