### ISSUE TITLE
requests.get失败

### ISSUE THREAD

**Issue by Erician** [qiniu/python-sdk#288]
使用下面的代码来获取response
r = requests.get(private_url,stream=True,timeout=60)
我有一个１ＧＢ的大文件，获取它的response有时成功，有时失败（就是一直没响应，直到超时）。对于小一点的文件是没有问题的，这个是为什么？

**Comment by bernieyangmh** [comment]
您好，有关requests的问题和七牛无关，您可以去[requests](https://github.com/requests/requests)的项目下提issue。

也许这个[问题](https://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py)能帮助你，可以看下
