### ISSUE TITLE
How to overwrite file which already exists

### ISSUE THREAD

**Issue by jxltom** [qiniu/python-sdk#301]
Currently, ```put_file``` method will raise error if file already exists. Is there an option for overwrite it?

**Comment by jemygraw** [comment]
when you generate the `uptoken`, set the parameter `key` in method `upload_token` the same value as it is in method `put_file` 

```
def upload_token(self, bucket, key=None, expires=3600, policy=None, strict_policy=True):
```

BTW, remember to refresh the access link if you have already visited the old file to make the new one take effect immediately.

**Comment by jxltom** [comment]
Thanks
