### ISSUE TITLE
bucket.list函数问题

### ISSUE THREAD

**Issue by HuismanKwl** [qiniu/python-sdk#310]
bucket.list函数入参的limit是1000，当最后一次返回的结果小于1000的时候，不会返回marker，那下次要继续获取的新增的文件名的时候，没有办法在之前的位置开始获取新增的文件名

**Comment by jemygraw** [comment]
marker是每次list中间的临时变量，不是全局的offset。所以无法返回。

**Comment by HuismanKwl** [comment]
那我要怎么才能继续上次的地方获取新增的文件名？

**Comment by jemygraw** [comment]
这个目前通过list接口无法做到，只能每次全量list。或者你指定规则，比如用日期作为前缀，这样每次list的会少一些，但是还是根据前缀list全部该前缀的文件。
