### ISSUE TITLE
upload时如何加上进度

### ISSUE THREAD

**Issue by Gourds** [qiniu/python-sdk#313]
下载的时候通过Request 及Contextlib可以实现，上传没有看到官方相关的接口，麻烦指点一下

**Comment by jemygraw** [comment]
上传方法里面有个参数 progress_handler ，函数原型是 def func(currentUploadedLength, totalLength) 只支持分片上传时候生效，表单上传文件太小的话，进度没有意义。

**Comment by Gourds** [comment]
@jemygraw 好的，谢谢
