### ISSUE TITLE
[pylint] E0611:No name 'DomainManager' in module 'qiniu'

### ISSUE THREAD

**Issue by YahuiWong** [qiniu/python-sdk#316]
![tim 20180904142248](https://user-images.githubusercontent.com/32868945/45013543-0acdd780-b04e-11e8-836b-048453af5b8d.png)
如图所示 当我使用 ```from qiniu import DomainManager ``` 的时候，提示 `No name 'DomainManager' in module 'qiniu'`  错误

是我使用的方式不对吗？希望可以帮忙解决，谢谢。

**Comment by YahuiWong** [comment]
@jemygraw

**Comment by ipcpu** [comment]
7.2.2版本中没有这个class，查找了源文件也没有，忘记放进去了吧？

**Comment by VincentSit** [comment]
从源码安装。

**Comment by YahuiWong** [comment]
> 从源码安装。

的确只能 从源码安装 才可以成功。。。
