### ISSUE TITLE
how to delete a bucket?

### ISSUE THREAD

**Issue by coderall** [qiniu/python-sdk#320]

**Comment by coderall** [comment]
the examples python file may not contain the content about how to delete a bucket

**Comment by Amren112** [comment]
Are u xiuer?

**Comment by forrest-mao** [comment]
Because delete bucket is a highly risky operation, we suggest u can delete bucket at [Qiniu Portal](https://portal.qiniu.com/kodo/bucket).
 
Please check documentation：https://developer.qiniu.com/kodo/manual/1233/console-quickstart#5
