### ISSUE TITLE
a bug in put_data

### ISSUE THREAD

**Issue by ArwenChan** [qiniu/python-sdk#324]
error in traceback:
    final_data += tmp_data
    TypeError: must be str, not bytes

which is caused by final_data initialed with string instead of bytes.

**Comment by liuchaotclc** [comment]
I have the same issue.Because calling request.files[name].stream return bytes.Don't know why

**Comment by liuchaotclc** [comment]
> I have the same issue.Because calling request.files[name].stream return bytes.Don't know why

save file in local.And then use put_file method. Method put_data is not official support

**Comment by weakish** [comment]
Why not support `put_date` officially? REST API and other SDKs (e.g.  Go SDK) supports this function.

**Comment by oubeichen** [comment]
想不通这个问题为啥一直没修，七牛都不用 python3 的吗

**Comment by lvyaoo** [comment]
请七牛的大佬们关注下这个bug

**Comment by a1401358759** [comment]
![image](https://user-images.githubusercontent.com/15830146/77840848-26637a80-71be-11ea-9057-7fbfacb042c0.png)
七牛的大佬们 我本地试过了这样改之后pyhton3可以上传 麻烦下个版本加一下吧

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-991

**Comment by a1401358759** [comment]
七牛的大佬们终于有时间关注这个bug了

**Comment by Mei-Zhao** [comment]
新版本v7.2.9修复了这个问题
