### ISSUE TITLE
qiniu 不支持python 3.6吗

### ISSUE THREAD

**Issue by yangqingbin** [qiniu/python-sdk#325]
![image](https://user-images.githubusercontent.com/39461869/50211537-d4755780-03b3-11e9-8ba9-a51e9a49b748.png)
导入qiniu 发现Ctrl 点击进入不了源码
各位大佬看下
使用pip install qiniu 安装的

**Comment by ramwin** [comment]
qiniu.py文件名和包名冲突，建议先把 qiniu.py更名

**Comment by Anlim** [comment]
@yangqingbin  Python version > 3.5 的问题有解决么？
我遇到了同样的问题，不过我使用的是 python 3.7

**Comment by ramwin** [comment]
> @yangqingbin Python version > 3.5 的问题有解决么？
> 我遇到了同样的问题，不过我使用的是 python 3.7

你先看下你的代码是不是正确吧。 @yangqingbin 他命名就是自己代码写错了

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-989
