### ISSUE TITLE
BucketManager 类的 fetch 方法的 docstring 有错误

### ISSUE THREAD

**Issue by stravel611** [qiniu/python-sdk#327]
Docstring 中对该方法的第一个返回值注释为： 

`一个dict变量，成功返回NULL，失败返回{"error":"<errMsg string>"}`

实际使用中发现应为：

`一个dict变量，类似 {"hash": "<Hash string>", "key": "<Key string>"}`

**Comment by forrest-mao** [comment]
收到，感谢提醒

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-992

**Comment by Mei-Zhao** [comment]
新版本v7.2.9修复了这个问题
