### ISSUE TITLE
这里不应该用post，会报协议错误，应该用get，但是http里边没有定义get协议的方法，所以需要进行调整

### ISSUE THREAD

**Issue by zhsh87** [qiniu/python-sdk#328]
def get_domain(self, name):
        """
        获取域名信息，文档 https://developer.qiniu.com/fusion/api/4246/the-domain-name
        Args:
           name:     域名, 如果是泛域名，必须以点号 . 开头
        Returns:
            返回一个tuple对象，其格式为(<result>, <ResponseInfo>)
            - result          成功返回dict{}，失败返回{"error": "<errMsg string>"}
            - ResponseInfo    请求的Response信息
        """
        url = '{0}/domain/{1}'.format(self.server, name)
        return self.__post(url)

**Comment by forrest-mao** [comment]
感谢提醒

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-993

**Comment by Mei-Zhao** [comment]
新版本v7.2.9修复了这个问题
