### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by YiniXu9506** [qiniu/python-sdk#333]
I used python SDK to upload a PDF to qiniu, but got the connection error.
The error message:

![image](https://user-images.githubusercontent.com/34967660/57224071-c8c0bf80-703a-11e9-9137-c10e17916f6e.png)

![image](https://user-images.githubusercontent.com/34967660/57224112-e8f07e80-703a-11e9-880c-bf34b907d5df.png)

This issue happened since 30th April, still not been fixed.  PTAL. Thanks!

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-994

**Comment by songfei9315** [comment]
3.6 我这边测试没有异常，你这边请求超时，可能是网络问题导致的，如果还能复现的话是否方便通过工单反馈给七牛的技术支持排查问题
https://support.qiniu.com/tickets/new
