### ISSUE TITLE
No JSON object could be decoded error because HTTP 502 is not handled correctly

### ISSUE THREAD

**Issue by jxltom** [qiniu/python-sdk#346]
THe qiniu might return 502 status such as the following response. In these circumstances, the ```response.text``` is not empty but it is not json at all, so https://github.com/qiniu/python-sdk/blob/ca80c00395df1a2be7d81970c92c38aa169a492f/qiniu/http.py#L235 will rasie ```ValueError("No JSON object could be decoded")``` error. This situation should be handled correctly.

```
u'<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
```

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-995

**Comment by Mei-Zhao** [comment]
新版本v7.2.9解决了这个问题
