### ISSUE TITLE
请问海外同步七牛云速度慢怎么解决？

### ISSUE THREAD

**Issue by zcleee** [qiniu/python-sdk#353]
我用的Github Actions自动同步到七牛云，但是速度有点慢！请问我应该修改哪一部分？

**Comment by forrest-mao** [comment]
因为 github 的服务器一般在海外，建议可以创建北美（更加推荐）或者东南亚的存储空间，然后使用 upload-na0.qiniup.com（北美）和 upload-as0.qiniup.com（东南亚）的上传域名将文件上传到七牛
