### ISSUE TITLE
为什么http._get里面不用session?

### ISSUE THREAD

**Issue by ramwin** [qiniu/python-sdk#358]
如题。我在调用[音频元信息](https://developer.qiniu.com/dora/api/1247/audio-and-video-metadata-information-avinfo)接口时，如果使用`_session.get`，10次请求只需要199ms，如果直接用`http._get`需要647ms。请问这个代码不用`_session`有什么特殊的考虑吗？能否修改一下？  
[源代码位置](https://github.com/qiniu/python-sdk/blob/master/qiniu/http.py#L76-L86)
```
def _get(url, params, auth):
    try:
        r = requests.get(
            url,
            params=params,
            auth=qiniu.auth.RequestsAuth(auth) if auth is not None else None,
            timeout=config.get_default('connection_timeout'),
            headers=_headers)
    except Exception as e:
        return None, ResponseInfo(None, e)
    return __return_wrapper(r)
```

运行结果图:
![运行结果图](https://github.com/ramwin/netdisk/blob/master/qiniu_session.png?raw=true)

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-1000

**Comment by Mei-Zhao** [comment]
新版本v7.2.9改善了这个问题
