### ISSUE TITLE
上传同名文件覆盖问题

### ISSUE THREAD

**Issue by ye-c** [qiniu/python-sdk#363]
上传同名文件，不是会自动覆盖么？可是外链显示还是最开始的图片呢，我想覆盖上传，请问要怎么做？

    key = 'lalala.png'
    qn = Auth(access_key, secret_key)
    token = qn.upload_token(bucket_name, key, 600)
    ret, info = put_file(token, key, filepath)
    # print(info)
    assert ret['key'] == key
    assert ret['hash'] == etag(filepath)

**Comment by ramwin** [comment]
因为cdn有缓存。只能够等一段时间等他刷新了

**Comment by chuifengji** [comment]
确定是缓存的问题？max-age我这边设置了没用。

**Comment by chuifengji** [comment]
怎么解决呢

**Comment by forrest-mao** [comment]
这个是因为有 CDN 的缓存，同名文件的覆盖上传后建议参考 https://developer.qiniu.com/fusion/kb/2501/refresh-the-prefetch 文档进行刷新操作、或者在 URL 后面加上新的 query 参数来做强制回源访问最新文件
