### ISSUE TITLE
请问sdk中调用上传可以设置路径前缀吗？

### ISSUE THREAD

**Issue by peteyan** [qiniu/python-sdk#380]
在页面中上传有个“设置路径前缀”选项（这里的路径前缀其实就是bucket name里面的文件夹路径），python sdk中uploader哪个方法带这个选项，谢谢。
sdk version: 7.2.10

**Comment by okbang9** [comment]
bucke里没有文件夹概念。key字段是可以拼接路径前缀的，uploader中包含key字段的上传函数或方法都支持。
