### ISSUE TITLE
utils-->_file_iter函数有BUG，读取input_stream后seek没有归0，导致后续需要使用input_stream的内容，读取不到数据。

### ISSUE THREAD

**Issue by IceRommy** [qiniu/python-sdk#387]
def _file_iter(input_stream, size, offset=0):
    """读取输入流:

    Args:
        input_stream: 待读取文件的二进制流
        size:         二进制流的大小

    Raises:
        IOError: 文件流读取失败
    """
    input_stream.seek(offset)
    d = input_stream.read(size)
    while d:
        yield d
        d = input_stream.read(size)
#while 结束后要加上 input_stream.seek(0)

**Comment by bachue** [comment]
@IceRommy  已经在最新版本里解决
