### ISSUE TITLE
How to download unlimited items from qiniu?

### ISSUE THREAD

**Issue by mosvict** [qiniu/python-sdk#390]
Hi Dear.
I have a question.
I tried to get items from qiniu bucket to download items.
But I got 1000 items.. I tried more but I can't get more items.
Please help me.

**Comment by yangjunren** [comment]
You can use this interface https://developer.qiniu.com/kodo/1284/list to specify the marker parameter returned from the previous enumeration to cyclely enumerate all the files in the obtained space。
demo reference：https://github.com/qiniu/python-sdk/blob/master/examples/list.py

**Comment by yangjunren** [comment]
You can use this interface https://developer.qiniu.com/kodo/1284/list to specify the marker parameter returned from the previous enumeration to cyclely enumerate all the files in the obtained space.
demo reference：https://github.com/qiniu/python-sdk/blob/master/examples/list.py

**Comment by mosvict** [comment]
Thanks
