### ISSUE TITLE
请问怎么在不确定域名的情况下，生成文件的外链

### ISSUE THREAD

**Issue by CMHopeSunshine** [qiniu/python-sdk#420]
假如有多个bucket，这些bucket不知道对应绑定的域名，如何生成该bucket中文件的外链？

**Comment by lihsai0** [comment]
暂时不能，目前缺失了[获取 bucket 绑定域名的能力](https://developer.qiniu.com/kodo/3949/get-the-bucket-space-domain)。

已记录问题，尽快安排。
