### ISSUE TITLE
希望尽快发布7.15版本—— py 7.14 windows兼容问题

### ISSUE THREAD

**Issue by creeponsky** [qiniu/python-sdk#453]
今天接入的时候发现windows环境下的7.14 会出现缓存文件读写和time格式问题
当我自己修复完成，发现7.15已经解决了，但是pypi上还未deploy
希望尽快🥲
感谢所有开发者的努力！

**Comment by lihsai0** [comment]
https://pypi.org/project/qiniu/7.15.0/
